name: Release Server
on:
  push:
    tags: "Server-*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --configuration Release 

    - name: Publish Server
      run: |
        ver=${GITHUB_REF#refs/tags/Server-}
        res=$(echo $ver | sed 's/-rc/./g')  
        dotnet publish --no-build ./MyServiceBus.Server/MyServiceBus.Server.csproj --output ./publish-api --configuration Release /p:AssemblyVersion=$res

    - name: ls
      run: ls ./publish-api
      
    - name: Publish Server to Registry
      uses: swisschain/Publish-Docker-Github-Action@master
      with:
        name: myjettools/my-service-bus
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: ./publish-api
        # snapshot: true # use snapshot to push an additional image, which is tagged with {YEAR}{MONTH}{DAY}{HOUR}{MINUTE}{SECOND}{first 6 digits of the git sha}
        tag_names: true  
        tag_name_skip: Server- 
